name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  # ARM Cross-Compile Build (does not run tests)
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (cross-compile)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            cmake make clang-tidy

      - name: Configure project (ARM toolchain)
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=arm64-toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build project (ARM)
        run: cmake --build build -- -j$(nproc)

      - name: Run clang-tidy
        run: clang-tidy hello.c -- -I.

  # Native GCC build for tests + coverage
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (native)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake make g++ gcc libgtest-dev clang-tidy lcov

      - name: Configure project (native with coverage)
        run: |
          cmake -B build-tests \
            -DCMAKE_BUILD_TYPE=Coverage \
            -DCMAKE_C_FLAGS="--coverage -O0 -g -fprofile-arcs -ftest-coverage" \
            -DCMAKE_CXX_FLAGS="--coverage -O0 -g -fprofile-arcs -ftest-coverage"

      - name: Build project (native)
        run: cmake --build build-tests -- -j$(nproc)

      - name: Run tests (JUnit XML + coverage)
        working-directory: build-tests
        run: ./test_hello --gtest_output=xml:results.xml

      - name: Publish test results to GitHub
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: gtest-report
          path: build-tests/results.xml
          reporter: jest-junit

      - name: Generate coverage report (HTML + info)
        run: |
          echo "Running lcov..."
          lcov --capture --directory build-tests --output-file build-tests/coverage.info
          lcov --remove build-tests/coverage.info '/usr/*' --output-file build-tests/coverage.info
          lcov --list build-tests/coverage.info
          genhtml build-tests/coverage.info --output-directory build-tests/coverage-html

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: build-tests/coverage.info
          flags: unittests
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Deploy coverage report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build-tests/coverage-html
