name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # ARM Cross-Compile Build (does not run tests)
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (cross-compile)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            cmake make clang-tidy

      - name: Configure project (ARM toolchain)
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=arm64-toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: Build project (ARM)
        run: cmake --build build -- -j$(nproc)

      - name: Run clang-tidy
        run: clang-tidy hello.c -- -I.

  # Native GCC build for tests + coverage
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies (native)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake make g++ gcc libgtest-dev clang-tidy lcov

      - name: Build and install GoogleTest
        run: |
          cd /usr/src/gtest
          sudo cmake .
          sudo make -j$(nproc)
          sudo cp lib/*.a /usr/lib

      - name: Configure project (native)
        run: cmake -B build-tests -DCMAKE_BUILD_TYPE=Coverage

      - name: Build project (native)
        run: cmake --build build-tests -- -j$(nproc)

      - name: Run tests with XML report
        run: ./build-tests/test_hello --gtest_output=xml:build-tests/results.xml

      - name: List build-tests directory (debug)
        run: ls -la build-tests

      - name: Publish test results to GitHub
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: gtest-report
          path: build-tests/results.xml
          reporter: jest-junit

      - name: Generate coverage report
        run: |
          cd build-tests
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build-tests/coverage.info
          token: ${{ secrets.CODECOV_TOKEN }} # only needed for private repos
